services:
  - id: tsp-mooc-db
    completeName: Relational Database
    port: 8080
    stack:
      - containerName: tsp-moocdb-postgres
        image: fmonniot/tsp-moocdb-postgres:latest
      - containerName: tsp-moocdb-web
        image: fmonniot/tsp-moocdb-web:latest
        ports:
          - "8080:80"
        links:
          - tsp-moocdb-postgres
  - id: nginx
    completeName: Nginx demo
    port: 8081
    stack:
      - containerName: nginx-demo
        image: nginx:latest
        ports:
          - "8081:80"
  - id: tsp-mooc-overview
    completeName: TSP MOOC Overview
    stack:
      - containerName: tsp-mooc-overview
        image: tsp-mooc-overview
